version: '3.8'

services:
  app:
    build:
      context:  ..
      dockerfile: .docker/Dockerfile
    container_name: urbanlegend_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - urbanlegend

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - urbanlegend
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: urbanlegend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: urbanlegend
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - urbanlegend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - urbanlegend

networks:
  urbanlegend:

volumes:
  dbdata:
